
package BackendGen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BackendService", targetNamespace = "http://com/", wsdlLocation = "http://localhost:8081/WebService_proj/?wsdl")
public class BackendService
    extends Service
{

    private final static URL BACKENDSERVICE_WSDL_LOCATION;
    private final static WebServiceException BACKENDSERVICE_EXCEPTION;
    private final static QName BACKENDSERVICE_QNAME = new QName("http://com/", "BackendService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WebService_proj/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BACKENDSERVICE_WSDL_LOCATION = url;
        BACKENDSERVICE_EXCEPTION = e;
    }

    public BackendService() {
        super(__getWsdlLocation(), BACKENDSERVICE_QNAME);
    }

    public BackendService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BACKENDSERVICE_QNAME, features);
    }

    public BackendService(URL wsdlLocation) {
        super(wsdlLocation, BACKENDSERVICE_QNAME);
    }

    public BackendService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BACKENDSERVICE_QNAME, features);
    }

    public BackendService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackendService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Backend
     */
    @WebEndpoint(name = "BackendPort")
    public Backend getBackendPort() {
        return super.getPort(new QName("http://com/", "BackendPort"), Backend.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Backend
     */
    @WebEndpoint(name = "BackendPort")
    public Backend getBackendPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/", "BackendPort"), Backend.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BACKENDSERVICE_EXCEPTION!= null) {
            throw BACKENDSERVICE_EXCEPTION;
        }
        return BACKENDSERVICE_WSDL_LOCATION;
    }

}
