
package BackendGen;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Backend", targetNamespace = "http://com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Backend {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.UserEntity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName="userInfo", targetNamespace = "http://com/", className = "BackendGen.UserInfo")
    @ResponseWrapper(localName = "userInfoResponse", targetNamespace = "http://com/", className = "BackendGen.UserInfoResponse")
    @Action(input = "http://com/Backend/userInfoRequest", output = "http://com/Backend/userInfoResponse")
    public List<UserEntity> userInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
